"""Add status and error_message to Game model

Revision ID: 04f74f37b8cc
Revises: bcb4545fb62f
Create Date: 2026-01-28 23:34:26.078148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f74f37b8cc'
down_revision = 'bcb4545fb62f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('status', sa.String(), nullable=True))
    op.add_column('games', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'error_message')
    op.drop_column('games', 'status')
    # ### end Alembic commands ###
