"""Add status and error_message to books table

Revision ID: 1176feea5285
Revises: 04f74f37b8cc
Create Date: 2026-01-31 02:57:05.132105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1176feea5285'
down_revision = '04f74f37b8cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('status', sa.String(), nullable=False))
    op.add_column('books', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'error_message')
    op.drop_column('books', 'status')
    # ### end Alembic commands ###
