"""Initial migration - create all tables

Revision ID: 8658cee1ef5c
Revises: 
Create Date: 2026-01-26 15:55:12.025588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8658cee1ef5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('book_id'),
    comment='Chess books uploaded for chatbot'
    )
    op.create_table('engine_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('fen', sa.String(), nullable=False),
    sa.Column('played_move', sa.String(), nullable=False),
    sa.Column('best_move', sa.String(), nullable=False),
    sa.Column('eval_before', sa.String(), nullable=False),
    sa.Column('eval_after', sa.String(), nullable=False),
    sa.Column('eval_best', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Cached Stockfish analysis results per move'
    )
    op.create_index(op.f('ix_engine_analysis_game_id'), 'engine_analysis', ['game_id'], unique=False)
    op.create_table('game_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('estimated_rating', sa.Integer(), nullable=True),
    sa.Column('rating_confidence', sa.String(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Game-level summary and statistics'
    )
    op.create_index(op.f('ix_game_summary_game_id'), 'game_summary', ['game_id'], unique=True)
    op.create_table('games',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('pgn', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('move_review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('centipawn_loss', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Classified moves with explanations'
    )
    op.create_index(op.f('ix_move_review_game_id'), 'move_review', ['game_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_type', sa.String(), nullable=True),
    sa.Column('context_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Chat messages for game review and book conversations'
    )
    op.create_index(op.f('ix_chat_messages_context_id'), 'chat_messages', ['context_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_context_type'), 'chat_messages', ['context_type'], unique=False)
    op.create_index(op.f('ix_chat_messages_game_id'), 'chat_messages', ['game_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_game_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_context_type'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_context_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_move_review_game_id'), table_name='move_review')
    op.drop_table('move_review')
    op.drop_table('games')
    op.drop_index(op.f('ix_game_summary_game_id'), table_name='game_summary')
    op.drop_table('game_summary')
    op.drop_index(op.f('ix_engine_analysis_game_id'), table_name='engine_analysis')
    op.drop_table('engine_analysis')
    op.drop_table('books')
    # ### end Alembic commands ###
