"""Add top_moves to engine_analysis

Revision ID: bcb4545fb62f
Revises: 8658cee1ef5c
Create Date: 2026-01-26 17:36:10.434269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb4545fb62f'
down_revision = '8658cee1ef5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engine_analysis', sa.Column('top_moves', sa.JSON(), nullable=True))
    op.add_column('engine_analysis', sa.Column('played_move_eval', sa.String(), nullable=True))
    op.add_column('engine_analysis', sa.Column('played_move_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engine_analysis', 'played_move_rank')
    op.drop_column('engine_analysis', 'played_move_eval')
    op.drop_column('engine_analysis', 'top_moves')
    # ### end Alembic commands ###
